### ISSUE TITLE
You have exceeded limit.

### ISSUE THREAD

**Issue by sayakbiswas13** [nitish24p/react-native-upi#53] opened 2023-09-11 07:52 UTC
I am getting this error of , You have exceeded daily limit of the bank. Please fix this issue if you know what it is. I need to use this package.

**Comment by sayakbiswas13** [comment] 2023-09-11 07:53
@nitish24p please help me with this.

**Comment by nitish24p** [comment] 2023-09-19 07:28
@sayakbiswas13
Can you put a breakpoint here https://github.com/nitish24p/react-native-upi/blob/master/android/src/main/java/com/upi/payment/UpiPaymentModule.java#L78 and post the payload here..

Closing since its a duplicate of 
https://github.com/nitish24p/react-native-upi/issues/46

**Closed by nitish24p** 2023-09-19 07:28 UTC
